In [1]:
import pandas as pd

In [20]:
df1= pd.read_csv("overall_hn_ratios.csv")

In [21]:
df1.head()

,GeneID,CIT1,C1T2,C1T3,C2T1,C2T2,C2T3,C3T1,C3T2,C3T3,...,C28T13,C28T14,C28T15,C28T16,C28T17,C28T18,C28T19,C28T20,C28T21,C28T22
0,LOC101497325,1.333333,4.000000,0.363636,0.666667,2.000000,0.181818,1.666667,5.000000,0.454545,...,4.000000,1.600000,0.888889,0.800000,8.000000,2.000000,1.600000,0.533333,0.888889,0.470588
1,LOC101488339,0.848101,0.788235,0.779070,0.443038,0.411765,0.406977,1.215190,1.129412,1.116279,...,2.175000,3.000000,1.160000,1.851064,43.500000,1.500000,3.954545,2.351351,2.175000,1.581818
2,LOC101488545,1.540984,2.043478,1.446154,0.983607,1.304348,0.923077,1.491803,1.978261,1.400000,...,1.390244,1.628571,2.192308,1.140000,57.000000,3.000000,1.965517,1.583333,1.727273,0.919355
3,LOC101497647,0.987261,1.040268,2.348485,0.872611,0.919463,2.075758,0.980892,1.033557,2.333333,...,0.672727,0.552239,0.440476,0.787234,6.166667,1.480000,0.948718,0.370000,0.606557,0.318966
4,LOC101489113,1.451292,1.206612,1.651584,1.063618,0.884298,1.210407,1.512922,1.257851,1.721719,...,0.442857,0.454927,0.306065,0.591281,36.166667,0.854331,1.212291,0.443763,0.783394,0.423002

In [22]:
df2= pd.read_csv("hn_ratio_overll_2.csv")

In [23]:
df2.head()

,C1T1,C1T2,C1T3,C1T4,C1T5,C1T6,C1T7,C1T8,C1T9,C1T10,...,C16T14,C1T1.1,C1T2.1,C1T3.1,C2T1.1,C2T2.1,C2T3.1,C3T1.1,C3T2.1,C3T3.1
0,1.120000,0.282828,0.072165,0.205882,0.266667,0.651163,0.139303,0.151351,0.077348,0.608696,...,0.780488,0.375000,0.171429,18.000000,0.458333,0.209524,22.000000,5.916667,2.704762,284.000000
1,1.221429,3.507692,1.387424,1.954286,7.600000,1.503297,1.060465,3.420000,4.920863,1.776623,...,1.095541,0.453039,0.429319,32.800000,0.426796,0.404450,30.900000,1.200276,1.137435,86.900000
2,1.094828,0.918626,2.180258,2.257778,5.029703,1.266833,1.157175,1.472464,4.163934,1.498525,...,1.060325,0.515432,0.498507,41.750000,0.635802,0.614925,51.500000,2.429012,2.349254,196.750000
3,1.185729,4.767932,0.389924,0.459536,19.824561,1.554333,1.484888,4.556452,5.566502,1.584853,...,1.008580,1.286364,1.141129,283.000000,1.550000,1.375000,341.000000,2.168182,1.923387,477.000000
4,1.016820,0.961909,23.609467,39.900000,15.000000,1.037172,1.281722,1.384455,17.051282,1.139674,...,0.803514,0.676174,0.606454,85.611111,1.059675,0.950413,134.166667,2.504607,2.246360,317.111111

In [24]:
combined_df = pd.concat([df1, df2], axis=1)  # axis=1 for columns

In [25]:
combined_df.head()

,GeneID,CIT1,C1T2,C1T3,C2T1,C2T2,C2T3,C3T1,C3T2,C3T3,...,C16T14,C1T1.1,C1T2.1,C1T3.1,C2T1.1,C2T2.1,C2T3.1,C3T1.1,C3T2.1,C3T3.1
0,LOC101497325,1.333333,4.000000,0.363636,0.666667,2.000000,0.181818,1.666667,5.000000,0.454545,...,0.780488,0.375000,0.171429,18.000000,0.458333,0.209524,22.000000,5.916667,2.704762,284.000000
1,LOC101488339,0.848101,0.788235,0.779070,0.443038,0.411765,0.406977,1.215190,1.129412,1.116279,...,1.095541,0.453039,0.429319,32.800000,0.426796,0.404450,30.900000,1.200276,1.137435,86.900000
2,LOC101488545,1.540984,2.043478,1.446154,0.983607,1.304348,0.923077,1.491803,1.978261,1.400000,...,1.060325,0.515432,0.498507,41.750000,0.635802,0.614925,51.500000,2.429012,2.349254,196.750000
3,LOC101497647,0.987261,1.040268,2.348485,0.872611,0.919463,2.075758,0.980892,1.033557,2.333333,...,1.008580,1.286364,1.141129,283.000000,1.550000,1.375000,341.000000,2.168182,1.923387,477.000000
4,LOC101489113,1.451292,1.206612,1.651584,1.063618,0.884298,1.210407,1.512922,1.257851,1.721719,...,0.803514,0.676174,0.606454,85.611111,1.059675,0.950413,134.166667,2.504607,2.246360,317.111111

In [26]:
combined_df.info

<bound method DataFrame.info of              GeneID      CIT1      C1T2      C1T3      C2T1      C2T2  \
0      LOC101497325  1.333333  4.000000  0.363636  0.666667  2.000000
1      LOC101488339  0.848101  0.788235  0.779070  0.443038  0.411765
2      LOC101488545  1.540984  2.043478  1.446154  0.983607  1.304348
3      LOC101497647  0.987261  1.040268  2.348485  0.872611  0.919463
4      LOC101489113  1.451292  1.206612  1.651584  1.063618  0.884298
...             ...       ...       ...       ...       ...       ...
28576    CiarC_p072  1.000000  1.000000  1.000000  1.000000  1.000000
28577    CiarC_p073  1.000000  1.000000  1.000000  1.000000  1.000000
28578    CiarC_t029  1.000000  1.000000  1.000000  1.000000  1.000000
28579    CiarC_p074  1.000000  1.000000  1.000000  1.000000  1.000000
28580    CiarC_p075  1.000000  1.000000  1.000000  1.000000  1.000000

           C2T3      C3T1      C3T2      C3T3  ...    C16T14    C1T1.1  \
0      0.181818  1.666667  5.000000  0.454545  ...  0.780488  0.375000
1      0.406977  1.215190  1.129412  1.116279  ...  1.095541  0.453039
2      0.923077  1.491803  1.978261  1.400000  ...  1.060325  0.515432
3      2.075758  0.980892  1.033557  2.333333  ...  1.008580  1.286364
4      1.210407  1.512922  1.257851  1.721719  ...  0.803514  0.676174
...         ...       ...       ...       ...  ...       ...       ...
28576  1.000000  1.000000  1.000000  1.000000  ...  1.000000  1.000000
28577  1.000000  1.000000  1.000000  1.000000  ...  1.000000  1.000000
28578  1.000000  1.000000  1.000000  1.000000  ...  1.000000  1.000000
28579  1.000000  1.000000  1.000000  1.000000  ...  1.000000  1.000000
28580  1.000000  1.000000  1.000000  1.000000  ...  1.000000  1.000000

         C1T2.1      C1T3.1    C2T1.1    C2T2.1      C2T3.1    C3T1.1  \
0      0.171429   18.000000  0.458333  0.209524   22.000000  5.916667
1      0.429319   32.800000  0.426796  0.404450   30.900000  1.200276
2      0.498507   41.750000  0.635802  0.614925   51.500000  2.429012
3      1.141129  283.000000  1.550000  1.375000  341.000000  2.168182
4      0.606454   85.611111  1.059675  0.950413  134.166667  2.504607
...         ...         ...       ...       ...         ...       ...
28576  1.000000    1.000000  1.000000  1.000000    1.000000  1.000000
28577  1.000000    1.000000  1.000000  1.000000    1.000000  1.000000
28578  1.000000    1.000000  1.000000  1.000000    1.000000  1.000000
28579  1.000000    1.000000  1.000000  1.000000    1.000000  1.000000
28580  1.000000    1.000000  1.000000  1.000000    1.000000  1.000000

         C3T2.1      C3T3.1
0      2.704762  284.000000
1      1.137435   86.900000
2      2.349254  196.750000
3      1.923387  477.000000
4      2.246360  317.111111
...         ...         ...
28576  1.000000    1.000000
28577  1.000000    1.000000
28578  1.000000    1.000000
28579  1.000000    1.000000
28580  1.000000    1.000000

[28581 rows x 1082 columns]>

In [27]:
import numpy as np

In [28]:
combined_df= combined_df.set_index('GeneID')
combined_df.head()

,CIT1,C1T2,C1T3,C2T1,C2T2,C2T3,C3T1,C3T2,C3T3,CIT1.1,...,C16T14,C1T1.1,C1T2.1,C1T3.1,C2T1.1,C2T2.1,C2T3.1,C3T1.1,C3T2.1,C3T3.1
GeneID,,,,,,,,,,,,,,,,,,,,,
LOC101497325,1.333333,4.000000,0.363636,0.666667,2.000000,0.181818,1.666667,5.000000,0.454545,1.000000,...,0.780488,0.375000,0.171429,18.000000,0.458333,0.209524,22.000000,5.916667,2.704762,284.000000
LOC101488339,0.848101,0.788235,0.779070,0.443038,0.411765,0.406977,1.215190,1.129412,1.116279,2.634146,...,1.095541,0.453039,0.429319,32.800000,0.426796,0.404450,30.900000,1.200276,1.137435,86.900000
LOC101488545,1.540984,2.043478,1.446154,0.983607,1.304348,0.923077,1.491803,1.978261,1.400000,1.783784,...,1.060325,0.515432,0.498507,41.750000,0.635802,0.614925,51.500000,2.429012,2.349254,196.750000
LOC101497647,0.987261,1.040268,2.348485,0.872611,0.919463,2.075758,0.980892,1.033557,2.333333,6.357143,...,1.008580,1.286364,1.141129,283.000000,1.550000,1.375000,341.000000,2.168182,1.923387,477.000000
LOC101489113,1.451292,1.206612,1.651584,1.063618,0.884298,1.210407,1.512922,1.257851,1.721719,1.313953,...,0.803514,0.676174,0.606454,85.611111,1.059675,0.950413,134.166667,2.504607,2.246360,317.111111

In [29]:
temp = pd.DataFrame()
thre = combined_df>=2
temp["up2"] = thre.sum(axis=1)

thre = combined_df>=5
temp["up5"] = thre.sum(axis=1)
thre = combined_df>=10
temp["up10"] = thre.sum(axis=1)

thre = combined_df<=1/2
temp["dn2"] = thre.sum(axis=1)

thre = combined_df<=1/5
temp["dn5"] = thre.sum(axis=1)
thre = combined_df<=1/10
temp["dn10"] = thre.sum(axis=1)

thre = combined_df >= 0
temp["all"] = thre.sum(axis=1)

temp["unchange2"] = temp["all"] - temp["up2"] - temp["dn2"]
temp["unchange5"] = temp["all"] - temp["up5"] - temp["dn5"]
temp["unchange10"] = temp["all"] - temp["up10"] - temp["dn10"]

temp["HN2"] = temp["up2"] - temp["dn2"]
temp["HN5"] = temp["up5"] - temp["dn5"]
temp["HN10"] = temp["up10"] - temp["dn10"]

temp

,up2,up5,up10,dn2,dn5,dn10,all,unchange2,unchange5,unchange10,HN2,HN5,HN10
GeneID,,,,,,,,,,,,,
LOC101497325,345,156,59,302,139,54,1081,434,786,968,43,17,5
LOC101488339,269,107,69,189,87,64,1081,623,887,948,80,20,5
LOC101488545,272,81,63,156,70,62,1081,653,930,956,116,11,1
LOC101497647,311,130,66,315,138,89,1081,455,813,926,-4,-8,-23
LOC101489113,286,157,127,171,102,78,1081,624,822,876,115,55,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...
CiarC_p072,0,0,0,6,0,0,1081,1075,1081,1081,-6,0,0
CiarC_p073,0,0,0,0,0,0,1081,1081,1081,1081,0,0,0
CiarC_t029,0,0,0,0,0,0,1081,1081,1081,1081,0,0,0
CiarC_p074,0,0,0,0,0,0,1081,1081,1081,1081,0,0,0
CiarC_p075,0,0,0,0,0,0,1081,1081,1081,1081,0,0,0

In [30]:
temp.to_csv("HN-score_drougt_cicer.csv", sep=",")